/*
 * defaultTitle
 *
 * defaultDescription
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	Films string `json:"films,omitempty"`

	Planets string `json:"planets,omitempty"`

	Species string `json:"species,omitempty"`

	Starships string `json:"starships,omitempty"`

	Vehicles string `json:"vehicles,omitempty"`

	People string `json:"people,omitempty"`
}
